/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jvvhkmmgeiebyunmigvm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnemV6dnlnZml3eGtueG5mYmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NjM4MzEsImV4cCI6MjA3NzEzOTgzMX0.LjpQ4gLDhGxK24g8w6mVzY64G2U4thmM_NHO2QylZNg"

// Environment variable fallbacks for client-side usage
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`
export const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || publicAnonKey
